AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template

Dissertation/part2.tex

В папке image лежит файл latex а не LaTeX. У меня не компилировался шаблон из-за этого.

Название картинки поменял на latex. было LaTeX

---

Dissertation/Makefile
Makefile
README.md
Synopsis/Makefile

Добавлены make-файлы, упоминание о них в README

---

Dissertation/Makefile
Synopsis/Makefile

Утилита `latexmk` поддерживает ключ `-C`, выполняющий очистку сгенерированных файлов. Иногда удобно ей пользоваться для полной пересборки документа.

Задача make clean для диссертации и автореферата

---

Makefile

fill some of standart GNU target  http://www.gnu.org/software/make/manual/html_node/Standard-Targets.html

root Makefile update

---

Dissertation/part1.tex

Двойка выпадала из-под знака корня

Typo in formula

---

Dissertation/appendix.tex

Длинные таблицы, которые были - с вертикальной разлиновкой и без поддержки пропорциональных абзацев. Сделал свою, добавил в приложение, проверил с xelatex и pdflatex + немного текста про то, что потребовалось допиливать.

longtabu appendix

---

to-booklet.sh

Делает из автореферата файл под брошюровку при печати на двухстороннем принтере.

add booklet script

---

common/characteristic.tex

Добавил комментарий о том, как сменить порядок разделов в сгруппированном списке литературы

Characteristic.tex

---

Dissertation/userstyles.tex

Без keepspaces=true пробелы съедаются
https://alexanius-blog.blogspot.ru/2012/09/lstlistings.html

Исправление отображения пробелов в кирилических коментариях в листинге

---

Makefile

Добавлены флаги `-halt-on-error` и `-file-line-error`.
`-halt-on-error` останавливает сборку сразу при появлении ошибки - не появляется интерактивной строки для ввода команд.
`-file-line-error` выводит информацию о месте ошибки.

Дополнительные опции при сборке

---

Dissertation/title.tex
Synopsis/title.tex
common/data.tex

Добавлен второй научный руководитель (с опциональными рамками вокруг фамилий) и третий оппонент.
Issue #205.

add second supervisor

---

Dissertation/title.tex
Synopsis/title.tex
common/data.tex

Добавлена вторая специальность на главной странице автореферата и диссертации. #246

добавлена вторая специальность

---

usercfg.mk

Добавлены правила `indent` и `compress`

add compress and indent rules

---

Makefile

for bash and windows commandline

improve Windows detection in Makefile

---

latexmkrc

Ещё два расширения добавлены в список `clean`. Появляются при генерации презентации.

presentation clean options

---

Makefile
Readme/Installation.md
unix.mk
usercfg.mk
windows.mk

- Правила сборки, доступные только в unix, перенесены в соответствующий файл.
- Изменена проверка операционной системы.
- Изменено правило для `compress`
- Подправлен `Installation.md`

move rules to unix.mk

---

examples.mk

Добавлены примеры сбора презентации с разными движками

add presentation example

---

Makefile
unix.mk
usercfg.mk

добавлен `help` для `unix`. сделан на основе [https://gist.github.com/klmr/575726c7e05d8780505a](https://gist.github.com/klmr/575726c7e05d8780505a)

add help for unix

---

unix.mk

Рецепт упрощён из-за возникающих проблем с форматом `&xelatex`

fix preformat for lualatex

---

Presentation/prescontent.tex
Presentation/prespreamble.tex
Presentation/setup.tex
common/setup.tex
presentation.tex

Добавлена возможность добавлять записи (notes) на слайд #257.
Управление осуществляется из файла **common/setup.tex**.

add presentation notes

---

Makefile
examples.mk
latexmkrc
usercfg.mk

Добавлена возможность управлять выводом заметок к презентации из #289 через Makefile

add support for noteon option

---

common/packages.tex

Патч для memoir, обсуждавшийся в #238 .

Иcправление положения якорей подписей (под)риcунков

---

presentation.tex

Убран footer из превого слайда презентации.

remove presentation titlepage footer

---

Makefile
examples.mk
usercfg.mk

Переименованы рецепты `_clean` и `_distclean`. #259

rename _clean and _distclean

---

unix.mk

Поправлен забытый при переименовании JOBNAME=>TARGET аргумент.

fix precompile jobname

---

Synopsis/content.tex
biblio/biblatex.tex
common/characteristic.tex
common/newnames.tex

Приведение имён некоторых макросов к виду, лучше соответсвующему общей системе имён;
замена табов на пробелы;
более аккуратные пробелы в получаемом pdf, в подсчёте количества публикаций.

Небольшой рефакторинг макросов библиографии

---

biblio/check-bib-dupes-and-usage.py

1. bib файлы открываются как utf8. 
Без этого, лично у меня, выскакивает [ошибка](https://stackoverflow.com/q/9233027/1032586) 
```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 126: character maps to <undefined>
```
2. починен случай строчки, когда слово `author` в некоторой строчке является не имененем поля (т.е. `  author = {Фамилия, И. О.},`) а чем-то ещё (например, у меня нашлась строчка 
`keywords = {AuthorAffilations.FEI,...`).
3. косметические изменения для лучшего соответствия PEP8

Небольшие исправления в check-bib-dupes-and-usage.py

---

Makefile
presentation_booklet.tex

Часто требуется печать презентации для комиссии. Добавлен рецепт для подготовки презентации к печати. Лист расположен вертикально, на листе по 2 слайда.

Добавлен рецепт presentation-booklet для печати презентации

---

dissertation.tex
presentation.tex
synopsis.tex

Добавлена команда вывода списка версий используемых библиотек.
Список версий можно легко найти в логе по строке `*File List*`.

Добавлена команда вывода списка версий используемых библиотек

---

biblio/biblatex.tex

Временное решение проблемы с biber. Пояснение в https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/issues/345

временное решение проблемы в biber

---

Readme/Links.md

Добавил ссылки на сайты-источники нормативных документов

---

biblio/biblatex.tex

Решение проблемы #362. Проверено на 2019 и 2018 texlive

fix biblatex foreach issue

---

Makefile
Synopsis/content.tex
Synopsis/setup.tex
examples.mk
latexmkrc
usercfg.mk

Добавлена опция `BIBGROUPED`, сбоирающая автореферат со сгруппированными авторскими работами. Вручную опцию можно включить в файле `Synopsis/setup.tex`

add bibgrouped Makefile option

---

biblio/biblatex.tex

fix \insertbiblioexternal numbering

---

examples.mk

Добавлен пропущенный пример сборки автореферата

добавлен пропущенный пример сборки

---

siunitx.cfg

Поправлен символ ангстрема, который ранее не выводился на экран

fix angstrom symbol

---

latexmkrc

fix subroutine redefine error in latexmkrc

---

Dissertation/references.tex
Readme/Bibliography.md
biblio/biblatex.tex

Собственно, этим коммитом предполагается закрыть #361.

[Docs] Обновил документацию о списка и подсписках литературы

---

common/packages.tex

fix #398
workaround suggested at https://github.com/latex3/babel/issues/51#issuecomment-589971931

Совместимость с babel 3.40 

---

Synopsis/content.tex
common/styles.tex

Выставлен соответствующий размер подписей подрисунков для диссертации и автореферата.

изменён размер подписей подрисунков в автореферате

---

common/data.tex

Использование текущего года на титульных страницах по-умолчанию.

использовать текущий год по-умолчанию

---

tikz.tex

Изменён тип документа в `tikz.tex` со `standalone` на `memoir`. Размер шрифтов, страницы и полей выставлен таким же, как в диссертации. Это упрощяет подбор размера рисунка.
Кроме того добавлены библиотеки tikz для графиков и электрических схем.

изменён тип документа для tikz.tex

---

.editorconfig

Добавлен файл настроек [`.editorconfig`](https://editorconfig.org/). Для поддерживаемых  редакторов настройки шаблона будут автоматически выставлены.

добавлен файл .editorconfig

---

README.md

актуализация структуры шаблона в readme

актуализация структуры шаблона в readme

---

Dissertation/disstyles.tex
Dissertation/introduction.tex
README.md
dissertation.tex

Добавление автоподсчёта приложений.
Данный PR закрывает issue: #331

автоматический подсчёт приложений

---

Dissertation/appendix.tex
dissertation.tex
examples.mk
synopsis.tex
tests/config.yml
tests/conftest.py
tests/test_pdf.py
tests/test_pdf.sh
unix.mk

Большая часть провеок сложноосуществима при наличии только pdf документа. Для упрощения тестирования были добавлены управляющие команды в текст шаблона. Например:
```latex
\begin{document}
\typeout{templatetest:page_numbering/disable:int:\arabic{page}} % контрольная команда для системы тестирования
\input{Synopsis/title}        % Титульный лист
%\mainmatter                  % В том числе начинает нумерацию страниц арабскими цифрами с единицы
% \typeout{templatetest:page_numbering/reset:int:\arabic{page}} % контрольная команда для системы тестирования
\mainmatter*                  % Нумерация страниц не изменится, но начнётся с новой страницы …
```

добавлена проверка нумерации страниц

---

common/characteristic.tex

Добавленный код не позволяет разрывать страницу перед списками в характеристике, чтобы заголовок не отрывался от списка.

Добавлен запрет разрыва страниц в характеристике

---

common/characteristic.tex
common/fonts.tex
common/packages.tex

Fix indentfirst problems in TL 2020
Fix #440
Fix #408

Indentfirst fix

---

biblio/biblatex.tex

Дополнение к #444. Поправлен вывод патентов и программ в общем списке работ автора
#444

поправлен вывод патентов и программ в общей библиографии

---

Dissertation/acronyms.tex

Выведение списка сокращений при  помощи окружения `description`.
Из минусов:
- при наличии формул в левой части приходится вручную выбирать размер `leftmargin`
- нельзя добавлять `minipage`
Из плюсов:
- не надо испольовать таблицы
- не надо использовать `minipage`
- отступы между строками такие же, как и для основного текста
#452

переделаны сокращения с использованием окружения description

---

Presentation/styles.tex

При защите могут возникнуть вопросы по списку публикаций. Поэтому важно, чтобы статьи в нём были пронумерованы.
В данном PR поставлен по-умолчанию нумерованный стиль списка статей с указаниями, как отключать нумерацию.

Презентация: изменён стиль списка литературы на нумерованный

---

compress.mk

Изменена команда конвертации с `ps2pdf` на `gs`. Это обусловлено тем, что `ps2pdf` по-умолчанию выбирает максимальную версию PDF файла. Кроме того, добавляемый флаг `-q` не позволяет следить за прогрессом конвертации.
По скольку `ps2pdf`  - это просто скрипт, запускающий `gs`, новых зависимостей это изменение не добавляет.
#295 

Изменена команда конвертации с ps2pdf на gc

---

Presentation/styles.tex

Добавлена настройка полей презентации

Добавлена настройка полей презентации

---

biblio/check-bib-dupes-and-usage.py

Утилита `check-bib-dupes-and-usage.py` полезна и действительно находит дубли, однако она выводит слишком мало информации. По результатам её работы трудно понять, что именно пошло не так (приходится вручную искать в библиографии фамилию автора и сравнить публикации). Особенно это проблематично, если один и тот же автор участвует во многих публикациях, некоторые из которых дублируются.
Я немого изменил формат хранимых данных и теперь она печатает намного более удобную информацию.
Было (фрагмент):
```
Duplicated record author: chirkova
with page: 187
with page: 200
Duplicated record author: vorontsov
with page: 167
with page: 180
with page: 181
with page: 181
with page: 187
with page: …
```

make output of bib-check more useful

---

.github/workflows/build.yaml

Добавил пример action (запускается руками из вкладки Actions) для сборки через workflow. Устаналивает texlive-full и другой софт для [ubuntu](https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/Readme/Installation.md#%D0%92-ubuntu). Собирает make, сохраняет все pdf как [артефакты](https://docs.github.com/en/actions/managing-workflow-runs/downloading-workflow-artifacts).

Add build action

---

Makefile

Исправлена следующая ошибка:
При вызове `make clean` и `make distclean`  не выполнялась очистка временных файлов для  `presentation_booklet` и  `presentation_handout`.  
issue не открывал, подходящего не нашел

Fixed make target  `clean` and `distclean` for `presentation_booklet` and `presentation_handout`
