AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template

- Dissertation/styles.tex
- Synopsis/styles.tex
Настроил использование Arial в качестве шрифта без засечек и Courier New в качестве моноширинного шрифта по умолчанию. Добавил костыль для polyglossia, явно указывающий использование кириллических символов в этих шрифтах, без этого не работает.
Никто не запрещает конечному пользователю использовать любимый Comic Sans MS для основного текста и Webdings для остального — теперь это даже проще.
> Некоторые начертания в XeTeX по умолчанию

- Dissertation/styles.tex
onehalfspacing уже задан в packages.tex, так что больше ничего на эту тему не надо.
Мой редактор по умолчанию при сохранении убирает пробелы из концов строк. Я нечаянно это закомитил. Если принципиально, просто выбросьте и руками уберите linespread.
> Удалён linespread из styles.tex, ибо он дублирует onehalfspacing 

- BibTeX-Styles/utf8gost71u.bst
Для правильной локализации обязательно указание языка.
```
@online{NuGet,
title = {Менеджер пакетов NuGet},
url   = {https://www.nuget.org/},
urldate = {29.07.2015},
language = "russian"
}
```
В другие стили семейства utf8gost*** переносится аналогично, если в этом возникнет необходимость.
> Поддержка @online в utf8gost71u.bst.

- Synopsis/Makefile
- Synopsis/draft.tex
Сильно порезаный шаблон ради скорости сборки. Только для автореферата. Надо, наверное, его еще дорабатывать, может что-то можно обратно включить, что не очень увеличивает время сборки, но заметно улучает черновик визуально. В целом процедура была проста - все внешние include перетащил  в draft.pdf, далее всё, что можно было закоментить - коментил. Если комментирование чего-то вызвало ошибку сборки - либло разкоментил, либо переопределял комманду).
Для текущей версии у меня на машине (всё с biber) - улучшение относительно исходного варианта - почти в 5 раз:
diser/Synopsis$ rm -rf *.pdf && make distclean && time make
чистовик xelatex ~ 11.5 сек.
diser/Synopsis$ rm -rf *.pdf && make distclean && time make pdf
чистовик pdflatex ~ 9.5 cек.
diser/Synopsis$ rm -rf *.pdf && make distclean && time …
> draft mode

- Installation.md
Не хватало '*' для выбора файлов по маске.
> Корректировка команд установки PSCyr

- common/styles.tex
При сборке с использованием `xelatex` задаётся параметр `\defaultfontfeatures`, активирующий лигатуры и подстановки вроде замены `--` на `–` и `"` на `“`. В связи с этим возникает нежелательная модификация листингов, набранных моноширинным шрифтом. Данный коммит исправляет проблему путём выбора шрифта *перед* установкой параметров по умолчанию.
> Исправить кавычки в verbatim при сборке XeTeX

- Dissertation/acronyms.tex
- Dissertation/part1.tex
- Dissertation/userpackages.tex
Из гост 5.4 Оформление списка сокращений и условных обозначений - "Перечень следует располагать столбцом." а это значит таблицей, которая может занимать несколько страниц. Добавил из своего дисера пример на 1.5 страницы, при этом пришлось поменять пакет для tabularx  + добавил пример использования alignedat в формулах.
> change acronyms

- common/setup.tex
Использовать latexmk для сборки удобно, но ещё удобнее не вносить правки в код для включения режима черновика:
* `latexmk -pdf -pdflatex="pdflatex %O '\newcounter{draft}\setcounter{draft}{1}\input{%S}'" -silent dissertation` для черновой сборки;
* `latexmk -pdf -pdflatex="xelatex %O %S" -silent dissertation` для чистовой сборки.
Чтобы такая возможность работала, нужно убедиться, что переменная `\thedraft` определена корректно. Для этого введена соответствующая проверка.
> Проверять наличие \thedraft для условной компиляции

- Dissertation/title.tex
- common/data.tex
Код, отвечающий за вывод УДК, закомментирован.
УДК указывать не требуется ни по ГОСТ 7.0.11,
ни по рекомендованному оформлению титульной страницы
из приложения к Положению о совете по защите диссертаций.
Добавление УДК [идёт по-видимому](https://github.com/latex-g7-32/latex-g7-32/issues/50#issuecomment-300282685) с времён использования ГОСТ 7.32 для оформления диссертаций за неимением иного.
> Удаление УДК с титульной страницы

- .gitattributes
В результате в архивах с релизами не появятся:
.gitattributes
.gitignore
LICENSE
CONTRIBUTING.md
Посмотреть, что попадает в архив возможно следующей командой:
`git archive --format=zip -o test.zip HEAD`
> Обновление .gitattributes

- common/packages.tex
- common/setup.tex
- common/styles.tex
Заведён ключ. позволяющий отключить использование pscyr
даже при корректной установке этого пакета.
Также появляется возможность управлять включением pscyr через Makefile.
> Контроль подключения пакета pscyr

- Dissertation/userpackages.tex
Теперь шрифт подписи о версии документа не изменяется
на страницах с листингами
> draft mode git mark font setting correction

- .gitignore
- Dissertation/Makefile
- Makefile
- Presentation/Makefile
- Synopsis/Makefile
- indent.yaml
Добавлен рецепт для выравнивания кода в `Makefile` при помощи `latexindent`.
Настройки выравнивания лежат в файле `indent.yaml`
По умолчанию рецепт запускает `latexindent` для каждого файла с расширением `.tex` в папках `Dissertation`, `Presentation` и `Synopsis`. Папки можно выбирать путём задания переменной `INDENT_DIRS`. Отдельные файлы можно выбрать путём задания переменной `INDENT_FILES`.
> Автоматическое выравнивание кода при помощи latexindent

- Makefile
- Readme/Installation.md
- common/fonts.tex
- common/setup.tex
- common/styles.tex
Шрифты семейства [liberation](https://pagure.io/liberation-fonts) метрически совместимы со шрифтами от ms.
Замена позволит упростить установку - эти шрифты предустановлены в большинстве дистрибутивов. Также они распространяются под свободной лицензией.
> Замена шрифтов на семейство Liberation

- common/packages.tex
Пакет impnattypo скоро, видимо, обновится и вернёт продвинутый функционал
для lualatex (https://github.com/raphink/impnattypo/pull/7).
Для этого и внесены правки. В режиме черновика под lualatex получим дополнительную
информацию, за счёт выделений цветом.
> Оптимизация кода для расстановки переносов и длины последней строки абзаца

- biblio/biblatex.tex
Добавлена совместимость с xelatex|lualatex (точнее с polyglossia).
По наводке #227
Автореферат не затронут, поскольку модифицирован вывод команды \insertbibliofull
> Bugfix: Управление заголовком списка литературы в диссертации

- presentation.tex
Починка внесённой в GH-248 несовместимости с LuaTex.
> В презентации добавлен аргумент `utf8` необходимый LuaTex

- Makefile
Перенесено правило `all` для `make`. В нынешнем состоянии по умолчанию выполняется первое правило из `usercfg.mk`, т.е. `indent`.
> move all rule

- windows.mk
Версия `indent:` для Windows вполне рабочая. [Править](https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/pull/259#issuecomment-473290701), имхо, не требуется - я только раскомментировал.
> indent для Widows (просто раскомментирован)

- usercfg.mk
Исправление `compress:` для Windows.
Было так:
```
>gnuwin32-make compress
!Error: no output file specified.
Usage: ps2pdf14 [options] <inputfile> <outputfile>
<inputfile> can be either a PS, EPS, or PDF file.
A single hyphen (-) denotes stdin.
<outputfile> is required if <inputfile> is a PDF file
or input is read from stdin.
gnuwin32-make: *** [compress] Ошибка 1
```
[Проблем с `/`](https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/pull/259#issuecomment-471678781) я не увидел, но оно хочет именно `ps2pdf [options] input.pdf output.pdf`, а через `-sOutputFile` не хочет. На CentOS7 работает и так и так.
> Исправление `compress:` для Windows

- biblio/othercites.bib
В пакете [**biblatex-gost**](https://www.ctan.org/pkg/biblatex-gost) улучшиласть поддрежка ссылок на диссертации и патенты. Добавлены примеры их использования.
> add new biblatex-gost examples

- biblio/othercites.bib
Убран символ `@` из комментариев, чтобы не возникало [проблем](https://tex.stackexchange.com/a/21710/104425) с `bibtex`. Подробнее в комментариях к  #282
> fix comments for bibtex

- biblio/biblatex.tex
- common/newnames.tex
Чинятся следующие баги из GH-282 :
1. все буквосочетания `notvak` были заменены на `others`, но одно осталось и это ломает `\insertbiblioauthorgrouped`. 
2. В `\insertbiblioauthorgrouped` 3 раза подряд используется заголовок `\vakbibtitle`. (так же косвенно связано с #306)
> Чиним insertbiblioauthorgrouped

- biblio/biblatex.tex
- common/characteristic.tex
1. Убраны ни на что не влияющие `\printbibliography` из refsection 2. Они там, вроде бы, всяко не нужны - там ни выводить, ни просто подсчитывать источники не нужно. Они только Warning'и ненужные кидают, даже когда `\insertbiblioauthorimportant` не используется.
2. Единый пустой `nobibheading` - создавать несколько одинаковых пустых смысла нет, я так понимаю.
3. Немного почищен код в `biblatex.tex`.
>  Косметические изменения в макросах библиографии

- biblio/biblatex.tex
Проворонил я в 04bbf56 `\printbibliography[heading=counter`. Что [сломало](https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/pull/312#issuecomment-489417392) диссертацию.
Здесь и этот заголовок библиографии заменется на единый `nonbibheading`.
> Замена последнего забытого пустого bibheading "counter" на nonbibheading

- biblio/biblatex.tex
- common/newnames.tex
- common/renames.tex
* Конструкция `\MakeLowercase{\protect\bibtitleauthor{}}` не срабатывала - буквы не становились маленькими. И оно было единственной строкой захардкоденной в `biblatex.tex ` строкой.
* прочий мелкий рефакторинг
> Рефакторинг макросов библиографии

- Synopsis/content.tex
- biblio/biblatex.tex
- common/characteristic.tex
- common/newnames.tex
1.  Исправление бага с неправильным заголовком библиографии, посаженного в c1aa9aab7f9649c747275caaf25f7cdf2b325533 .
2. Пара мелких косметических правок, для получения более однородного стиля
> Исправление бага с неправильным заголовком \insertbiblioexternal

- Presentation/prespreamble.tex
Предложенное в [tex.so](https://tex.stackexchange.com/a/306662/104425) решение проблемы с исчезновением текста в презентации (#299) заработало после вынесения его за блок `\ifnumequal`
> beamer xelatex workaround fix

- Presentation/prescontent.tex
- Presentation/prespreamble.tex
- Presentation/setup.tex
Изменён первый слайд презентации. Добавлен логотип. Пользователь при желании теперь может изменять положение элементов  на первом слайде в файле `Presentation/prespreamble.tex`.
На остальные слайды тоже добавлен логотип.
Вывод логотипов контролируется двумя переменными в файле `Presentation/setup.tex`.
> Оформление первого слайда презентации через \setbeamertemplate

- .gitignore
Данное изменение позволяет игнорировать файлы с расширением `.pdf`,  `.ps` и  `.eps` только в корневом каталоге. git будет следить за изменениями файлов с этими расширениями в остальных директориях. Например, в `images`.
> ignore .pdf .ps .eps in root folder only

- Dissertation/part1.tex
- common/packages.tex
При использовании latexindent с включённым [text wrap](http://mirror.macomnet.net/pub/CTAN/support/latexindent/documentation/latexindent.pdf#subsection.6.1) разбиваются ссылки в команде `\labelcref` из-за отсутствия пробелов между ссылками.
Проблема решается добавлением возможности использования пробелов в `\labelcref`.
Решение взято [отсюда](https://tex.stackexchange.com/a/340502/104425).
> добавлена возможность использования пробелов в \labelcref

- indent.yaml
- unix.mk
- windows.mk
Добавлен рецепт для разбиения длинных строк в исходных файлах при помощи `latexindent`.
Максимальная длина строки составляет 80 символов.
> добавлен рецепт для разбиения длинных строк в исходных файлах

- common/packages.tex
При использовании двух ссылок в команде `\labelcref` возникает ошибка
```
! LaTeX Error: Command \cyri unavailable in encoding TU.
```
Подробнее проблема описана [здесь](https://tex.stackexchange.com/q/455092/104425).
Данный PR решает эту проблему для `xelatex` и `lualatex`.
P.S. при возникновении подобных ошибок в дальнейшем вожможно лучше использовать предоставленный в [ответе на SO](https://tex.stackexchange.com/a/455124/104425) файл `tucyradd.def`.
> решение проблемы с двумя ссылками в \labelcref

- Dockerfile
- Readme/Installation.md
- install-dockertex.sh
Этот коммит результат обсуждения проблемы #305. 
В итоге я пришел к следующему решению - используем образ Docker-контейнера от проекта `dockertex` (как я уже писал [в комментарии](https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/issues/305#issuecomment-515779775)) с минимальной модификацией - добавлением пакета шрифтов от Microsoft - `ttf-mscorefonts-installer` и набора шрифтов Liberation в виде пакета `fonts-liberation`.
Добавилось два файла:
1. `Dockerfile` с описанием модификации контейнера;
2. `install-dockertex.sh` со скриптом автоматизированной установки Docker и dockertex в систему. Для удобства пользователя он задает версию контейнера переменной окружения и сохраняет его в соответствующих файлах - `~/.profile` и `~/.bashrc`.
Актуализировано содержимое …
> added dockertex - fix for #305

- .gitignore
- Dissertation/dispackages.tex
- Dissertation/part2.tex
- Presentation/content.tex
- Presentation/images/tikz_plot.tikz
- Presentation/prespackages.tex
- common/packages.tex
- images/cache/placeholder.txt
При прекомпиляции изображений библиотека [`tex-external`](http://mirror.macomnet.net/pub/CTAN/graphics/pgf/base/doc/pgfmanual.pdf) запускает дочерний процесс `latex` для генерации изображений. Если прекомпиляция была включена из командной строки при помощи `IMGCOMPILE=1`, а в `common/setup.tex` она отключена, то в дочернем процессе значение`imgprecompile` будет равно `0`, из-за чего библиотека `tex-external` в нём будет отключена. Вместо изображения в конечный файл будет добавлен весь документ (то, что влезет на одну страницу):
В данном PR добавлено автоматическое переключение флага `imgprecompile` при определении данного процесса как дочернего при помощи проверки наличия `\tikzexternalrealjob`:
```
\tikzexternalrealjob
After the library is loaded, this macro will always contain the …
```
> поправлена прекомпиляция изображений из Makefile

- latexmkrc
Вызов прекомпиляции изображений в `latexmk` приведён в соответствие с аналогичными командами в этом файле. Избавляет от ошибок в случае запуска `make IMGCOMPILE=y`.
> изменён вызов прекомпиляции в latexmkrc

- biblio/biblatex.tex
Подавляющее большинство ссылок обычно идёт на текст статей, книг и т.д. В связи с этим оправданным является использование типа материала `media=text` по-умолчанию.
> use media=text by default

- Dissertation/part1.tex
- Dissertation/part3.tex
- Dissertation/userstyles.tex
- Presentation/prespackages.tex
- common/packages.tex
- common/styles.tex
- siunitx.cfg
Макро `\slantfrac` заменено пакетом `units`. Добавлены примеры
применения.
Один из примеров также демонстрирует возможности команды `\subequations`
---
> добавлен пакет units и пример subequations

- biblio/biblatex.tex
Possible fix https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/issues/360
Possible fix https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/issues/372
Possible fix https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/issues/374
`make examples-pdflatex-cm` срабатывает корректно.
`pdflatex`, `inputenc`, `babel` или вообще кодировка T2A в 2019 году перестали в каких-то случаях нормально работать как минимум со знаком номера (№), что проявлялось в работе с biblatex-gost.
Решение проблемы подсказано в https://github.com/odomanov/biblatex-gost/issues/22#issuecomment-555391235
> Fix incorrect support of numero sign in russian pdflatex

- biblio/biblatex.tex
Проверено на pdflatex через движок biber. [Взято тут](https://github.com/odomanov/biblatex-gost/wiki/%D0%9A%D0%B0%D0%BA-%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C,-%D1%87%D1%82%D0%BE%D0%B1%D1%8B-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D1%8F%D0%B7%D1%8B%D1%87%D0%BD%D1%8B%D0%B5-%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%B8-%D0%BF%D1%80%D0%B5%D0%B4%D1%88%D0%B5%D1%81%D1%82%D0%B2%D0%BE%D0%B2%D0%B0%D0%BB%D0%B8-%D0%BE%D1%81%D1%82%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%BC)
> Русскоязычные источники предшествуют остальным

- common/packages.tex
При сборке последней версии шаблона выводится ошибка:
```
Package fontspec Info: Adjusting the maths setup (use [no-math] to avoid
(fontspec)             this).
\symlegacymaths=\mathgroup7
LaTeX Font Info:    Overwriting symbol font `legacymaths' in version `bold'
(Font)                  OT1/cmr/m/n --> OT1/cmr/bx/n on input line 52.
./dissertation.tex:52: LaTeX Error: Command `\acute' already defined.
```
Решение проблемы при помощи <https://tex.stackexchange.com/a/26295/104425>
> Решение проблемы со сборкой

- Dissertation/part1.tex
- Dissertation/part3.tex
- common/packages.tex
Добавление команд \refs и \eqrefs для ссылок на несколько источников/уравнений. Команды добавляют читаемости коду. Реализованы при помощи `\labelcref`.
> добавление команд \refs и \eqrefs

- Makefile
- latexmkrc
Добвален флаг USEDEV для использования dev версий latex. Подробнее в #394
> добавлен флаг USEDEV

- Presentation/prespackages.tex
Исправление ошибки из PR #402, описанной в  #404
> переименование \todo в \fixme для презентации

- common/packages.tex
Согласно [ГОСТ](https://github.com/AndreyAkinshin/Russian-Phd-LaTeX-Dissertation-Template/blob/master/Documents/GOST%202.105-95.pdf):
> 4.2.11 Если в тексте документа приводят диапазон числовых значений физической величины, выраженных в одной и той же единице физической величины, то обозначение единицы физической
В данном PR настройки пакета `siunitx` изменены, чтобы соответствовать этим требованиям.
> изменение форматирования диапазонов чисел

- Readme/Bibliography.md
Добавлено решение проблемы со сборкой библиографии при использовании редактора WinEdt с MikTEX.
- [1 ] Feature
-
-
-
- [ 1] Windows
> Переключение на biber в WinEdt

- compress.mk
1. В `compress.mk` добавлена переменная `COMPRESSION_IMAGE_DPI` для управления DPI изображения из командной строки.
2. Код изменён так, чтобы параметр `COMPRESS_FILE` принимал в качестве аргумента название файла как с расширением `.pdf`, так и без.
> добавление переменной для управления сжатием рисунков в make

- Dissertation/renames.tex
- common/renames.tex
- dissertation.tex
- synopsis.tex
Fix #510
Как-то упустили, чт ов автореферате подписи у рисунков были не такими как в диссертации (и требуется по ГОСТ).
> Исправление подписей рисунков и таблиц автореферата

- common/characteristic.tex
- Убраны команды \sloppy из файла characteristic чтобы не словить неожиданностей в будущем: https://tex.stackexchange.com/a/241355 (если прям надо будет, то лучше будет обрамить в sloppypar окружение)
- с каким-то из новых biblatex в "невидимых" \prinbibliography появляется как будто \par. Это видно на свежем TeXLive2024 обновленном. Правка обрамляет в \phantom, чтобы невидимость получить иначе. На TexLive 2023 проверено что изменений не видно
> Fix biblatex refsection extra par
